/**
 * 文書に載せたコード例が、いまの公開 API で本当にコンパイルできるかを確かめる。
 *
 *   node scripts/check-docs.mjs
 *
 * なぜ要るか。
 *
 * README と docs/ は「外から見た kasane」そのものであり、利用者が最初に写すコードでもある。
 * ところが型チェックの対象は src / tests / examples だけで、**文書の中のコードは誰も見ていなかった**。
 * 実際この検査を入れた初回に、README のシート例が
 * `Property 'children' is missing in type '{}' but required in type 'ModalBodyProps'`
 * で落ちた。公開してから利用者が踏む類の壊れ方で、既存のどのゲートにも引っかからない。
 *
 * やること。
 *   1. README.md と docs/*.md から tsx / ts / jsx のコードブロックを抜く
 *   2. kasane 以外のパッケージを import しているブロックは対象外にする（未インストールのため）
 *      — ただし黙って飛ばさず、件数と場所を必ず出す
 *   3. 残りを 1 ブロック 1 ファイルに展開し、tsc に通す
 *
 * 文書は断片なので、宣言されていない識別子（`setOpen` など）は PLACEHOLDERS で補う。
 * 新しい placeholder が要るときは tsc が名前を挙げて落ちるので、そこで気づける。
 */
import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

/** ここを下回ったら、抽出の正規表現が壊れたと判断する（素通りを防ぐ）。 */
const MIN_BLOCKS = 18;

const OUT = '.tmp-doccheck';

const sources = ['README.md', ...readdirSync('docs').filter((f) => f.endsWith('.md')).map((f) => join('docs', f))];

/**
 * 文書が省いている変数。kasane の API ではないので、ここで宣言だけ与える。
 * 本物の API がここに混ざらないよう、kasane が export する名前は書かない。
 */
const PLACEHOLDERS = `
declare const save: () => void;
declare const selected: string[];
declare const setSelected: React.Dispatch<React.SetStateAction<string[]>>;
declare const listRef: React.RefObject<HTMLUListElement | null>;
declare const MyBarChart: React.FC;
declare const open: boolean;
declare const setOpen: (v: boolean) => void;
declare const name: string, setName: (v: string) => void, nameError: string;
declare const memo: string, setMemo: (v: string) => void;
declare const newsletter: boolean, setNewsletter: (v: boolean) => void;
declare const KINDS: { value: string; label: string }[];
declare const SHIPPING: { value: string; label: string }[];
declare const shipping: string, setShipping: (v: string) => void;
declare const notify: boolean, setNotify: (v: boolean) => void;
declare const volume: number, setVolume: (v: number) => void;
declare const tz: string, setTz: (v: string) => void;
declare const fileName: string, setFileName: (v: string) => void;
declare const date: string, setDate: (v: string) => void;
declare const time: string, setTime: (v: string) => void;
declare const GENRES: { value: string; label: string }[];
declare const genres: string[], setGenres: (v: string[]) => void;
declare const ZONES: { value: string; label: string }[];
declare const CITIES: string[];
declare const range: number[], setRange: (v: number[]) => void;
`;

const PRELUDE = `/* generated by scripts/check-docs.mjs — do not edit */
import * as React from 'react';
import { useState, useRef, useCallback } from 'react';
import { Modal, useModals, useModalContext } from '@genelab/kasane';
${PLACEHOLDERS}
void [React, useState, useRef, useCallback, Modal, useModals, useModalContext];
`;

const TSCONFIG = {
  compilerOptions: {
    target: 'ES2022',
    lib: ['ES2022', 'DOM', 'DOM.Iterable'],
    module: 'ESNext',
    moduleResolution: 'Bundler',
    jsx: 'react-jsx',
    strict: true,
    noUncheckedIndexedAccess: true,
    // 文書は断片なので「使っていない」は正常。ここだけ緩める。
    noUnusedLocals: false,
    noUnusedParameters: false,
    skipLibCheck: true,
    noEmit: true,
    baseUrl: '..',
    paths: { '@genelab/kasane': ['./src/index.ts'] },
  },
  include: ['./*.tsx'],
};

let failed = false;
const fail = (message) => {
  failed = true;
  console.error(`  FAIL  ${message}`);
};

console.log('checking documented examples');

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });

const skipped = [];
const checked = [];

for (const src of sources) {
  const md = readFileSync(src, 'utf8');
  const re = /```(tsx|ts|jsx)\n([\s\S]*?)```/g;
  let match;
  let index = 0;
  while ((match = re.exec(md))) {
    index += 1;
    const raw = match[2];
    const where = `${src} #${index}`;

    // kasane 以外からの import があるブロックは、その依存が無いので検査できない。
    if (/^import .*from '(?!@genelab\/kasane)/m.test(raw)) {
      skipped.push(where);
      continue;
    }

    const id = `${src.replace(/[^a-z0-9]/gi, '_')}_${index}`;
    // kasane の import は PRELUDE が持っているので落とす（重複宣言になるため）。
    const body = raw
      .split('\n')
      .filter((line) => !/^import .*'@genelab\/kasane/.test(line))
      .join('\n')
      .trim();

    let wrapped;
    if (body.startsWith('<')) {
      // JSX 断片。兄弟要素が並ぶことがあるのでフラグメントで包む。
      wrapped = `export function Demo_${id}() {\n  return (\n    <>\n${body}\n    </>\n  );\n}\n`;
    } else if (/^(function|const|class|export|interface|type)\s/.test(body)) {
      wrapped = `${body}\n`;
    } else {
      // 手続きの断片。await を含むことがあるので async で包む。
      wrapped = `export async function demo_${id}() {\n${body}\n}\n`;
    }

    writeFileSync(join(OUT, `${id}.tsx`), `${PRELUDE}\n${wrapped}`);
    checked.push(where);
  }
}

writeFileSync(join(OUT, 'tsconfig.json'), JSON.stringify(TSCONFIG, null, 2));

if (checked.length < MIN_BLOCKS) {
  fail(`抽出できたブロックが ${checked.length} 件しかない（${MIN_BLOCKS} 件以上のはず）。抽出が壊れていないか確認する`);
}

try {
  execFileSync('npx', ['tsc', '-p', join(OUT, 'tsconfig.json')], {
    stdio: 'pipe',
    encoding: 'utf8',
  });
  console.log(`  ok    ${checked.length} 件のコード例が公開 API でコンパイルできる`);
} catch (error) {
  const out = `${error.stdout ?? ''}${error.stderr ?? ''}`.trim();
  // 生成ファイル名から、元の文書と何番目のブロックかに戻す。
  const lines = out.split('\n').filter(Boolean);
  fail('コンパイルできないコード例がある');
  for (const line of lines) {
    const hit = line.match(/^\.?[\\/]?(?:\.tmp-doccheck)[\\/]([A-Za-z0-9_]+)\.tsx\((\d+),/);
    if (hit) {
      const origin = checked.find((w) => w.replace(/[^a-z0-9]/gi, '_').startsWith(hit[1].split('_md_')[0]));
      console.error(`        ${line}${origin ? `   ← ${hit[1]}` : ''}`);
    } else {
      console.error(`        ${line}`);
    }
  }
}

if (skipped.length > 0) {
  // 飛ばしたことを隠さない。「検査した」と「検査していない」を混ぜない。
  console.log(`  --    ${skipped.length} 件は外部パッケージを import しているため対象外: ${skipped.join(', ')}`);
}

rmSync(OUT, { recursive: true, force: true });

if (failed) {
  console.error('\ndocs check failed.');
  process.exit(1);
}
console.log('\ndocs check passed.');
